### PR TITLE
Adding Collapsible file view

### LINKED ISSUE #180: Improve file explorer to have a collapsible view
Improve file explorer to have a collapsible view and support other features such as:

- Rename
- Directories
- Delete
- Create
- More

### PR DESCRIPTION
**Pull request by javizqh**
Resolves #180

### CODE REVIEW

**Comment by javizqh** [comment]
Screenshot from 2024-08-13 18-54-49

**Comment by javizqh** [comment]
Screenshot from 2024-08-21 19-32-03

**Comment by javizqh** [comment]
Features missing to the menu that provides extra actions:

- [ ] Popup modal to double check a delete
- [ ] Change New Action modal to handle the creation of other types
- [ ] Download Action: Offline right now is just a mv action, but online it will change
- [ ] Upload modal
- [ ] Rename modal
- [ ] Create directory popup modal
- [ ] Extra: Edit Action Modal Popup update to have more functionality, like renaming

**Comment by javizqh** [comment]
The behaviour of the drop files to upload is not consistent on Vivaldi, may need to check further, but in Firefox works fine

**Review by OscarMrZ — APPROVED** [review]
Great work! It looks amazing

**Pull request merged**
