### PR TITLE
Adding BT status visualization

### PR DESCRIPTION
**Pull request by javizqh**
Adding BT status visualization

### CODE REVIEW

**Comment by javizqh** [comment]
Still missing Comms Update

**Comment by javizqh** [comment]
Missing:

- [ ]  Change color when status change
- [ ]  Button to toggle view

**Comment by javizqh** [comment]
In order to test it, is needed to generate a miniRadi being in the branch https://github.com/JdeRobot/RoboticsAcademy/pull/2721 and in the RAM branch https://github.com/JdeRobot/RoboticsApplicationManager/pull/154

**Comment by javizqh** [comment]
The visualizer has been commented out because it is not fully functional.

Also added back almost all of the edit action functionality

**Comment by javizqh** [comment]
Features missing:

- [ ] Tag edit modal
- [ ] Actions accent color

**Comment by OscarMrZ** [comment]
Let's merge and work in the different issues separatedly.

**Pull request merged**
