### PR TITLE
Adding visual identifier to selected node

### PR DESCRIPTION
**Pull request by javizqh**
Adding a clear visual identifier that indicates when a node is selected.

Before it was impossible to differentiate between a selected node and one that was not.

before

And after:

after

### CODE REVIEW

**Comment by javizqh** [comment]
Changing header icons assets size to 25x25 in order for it to look properly in Chromium based browser like Vivaldi

**Comment by javizqh** [comment]
Added dropdown list for changing projects as with the approach used before there was no way of knowing the number of projects and needed the user to know the exact project name.

So this is the final result:
after_off
after_on

**Comment by jmplaza** [comment]
Maybe we should keep the service of dealing with several projects only for BT-Studio integrated at Unibotics online robotics webIDE...

**Comment by javizqh** [comment]
Reverting back the dropdown list feature

**Comment by OscarMrZ** [comment]
Hi @javizqh, great addition! Merging!

**Comment by OscarMrZ** [comment]
We should discuss in more detail the project dropdown, maybe it should be included in the offline version as it is a quite needed feature if we support multiproject. Anyhow, let's open another issue about that. 

Also, in the future please open an issue and link it to the PR so we can trace bugs and enhancements easier!

**Pull request merged**
